### PR TITLE
(GH-139) Use puppet-agent 7.15.0

### LINKED ISSUE #139: (BUG) Cannot run exec command with tool
**Describe the bug**
During the execution of the exec command I assume PRM builds the docker image in order to run the tool.  It appears as if that image build is failing and the image is never created therefore the tool cannot be run.

**To Reproduce**
1. Install prm on a clean system
2. Run prm exec puppetlabs/ra10ke
3. See error

**Expected behavior**
Would see output related to running ra10ke

**Screenshots or logs**
```
➜  ~ prm exec puppetlabs/ra10ke -d --log-level=debug
12:35AM DBG pkg/prm/prm.go:157 > Searching /home/user1/.puppetlabs/prm/tools for tool configs
12:35AM DBG pkg/prm/prm.go:163 > Found: /home/user1/.puppetlabs/prm/tools/nwops/debugger/0.1.1/prm-config.yml
12:35AM DBG pkg/prm/prm.go:163 > Found: /home/user1/.puppetlabs/prm/tools/nwops/debugger/0.1.2/prm-config.yml
12:35AM DBG pkg/prm/prm.go:163 > Found: /home/user1/.puppetlabs/prm/tools/puppetlabs/epp/0.1.0/prm-config.yml
12:35AM DBG pkg/prm/prm.go:163 > Found: /home/user1/.puppetlabs/prm/tools/puppetlabs/heira-eyaml/0.1.0/prm-config.yml
12:35AM DBG pkg/prm/prm.go:163 > Found: /home/user1/.puppetlabs/prm/tools/puppetlabs/metadata-json-lint/0.1.0/prm-config.yml
12:35AM DBG pkg/prm/prm.go:163 > Found: /home/user1/.puppetlabs/prm/tools/puppetlabs/onceover/0.1.0/prm-config.yml
12:35AM DBG pkg/prm/prm.go:163 > Found: /home/user1/.puppetlabs/prm/tools/puppetlabs/parser/0.1.0/prm-config.yml
12:35AM DBG pkg/prm/prm.go:163 > Found: /home/user1/.puppetlabs/prm/tools/puppetlabs/puppet-lint/0.1.0/prm-config.yml
12:35AM DBG pkg/prm/prm.go:163 > Found: /home/user1/.puppetlabs/prm/tools/puppetlabs/puppet-strings/0.1.0/prm-config.yml
12:35AM DBG pkg/prm/prm.go:163 > Found: /home/user1/.puppetlabs/prm/tools/puppetlabs/puppet-syntax/0.1.0/prm-config.yml
12:35AM DBG pkg/prm/prm.go:163 > Found: /home/user1/.puppetlabs/prm/tools/puppetlabs/r10k/0.1.0/prm-config.yml
12:35AM DBG pkg/prm/prm.go:163 > Found: /home/user1/.puppetlabs/prm/tools/puppetlabs/ra10ke/0.1.0/prm-config.yml
12:35AM DBG pkg/prm/prm.go:163 > Found: /home/user1/.puppetlabs/prm/tools/puppetlabs/rubocop/0.1.0/prm-config.yml
12:35AM DBG pkg/prm/prm.go:163 > Found: /home/user1/.puppetlabs/prm/tools/puppetlabs/spec_cache/0.1.0/prm-config.yml
12:35AM DBG pkg/prm/prm.go:163 > Found: /home/user1/.puppetlabs/prm/tools/puppetlabs/spec_puppet/0.1.0/prm-config.yml
12:35AM INF pkg/prm/docker.go:95 > Creating new image. Please wait...
12:35AM DBG pkg/prm/docker.go:101 > Creating Dockerfile
--------------------
FROM puppet/puppet-agent:7.0.0
RUN apt update
RUN apt install git -y
RUN /opt/puppetlabs/puppet/bin/gem install bundler --no-document
RUN /opt/puppetlabs/puppet/bin/gem install ra10ke -f --conservative --minimal-deps --no-document
RUN /opt/puppetlabs/puppet/bin/gem install rubygems-update -f --conservative --minimal-deps --no-document
COPY ./content/* /tmp/ 
VOLUME [ /code, /cache ]
WORKDIR /code
ENTRYPOINT ["/tmp/entrypoint.sh"]
CMD ["-T"]
--------------------

12:35AM DBG pkg/prm/docker.go:159 > Step 1/11 : FROM puppet/puppet-agent:7.0.0
12:35AM INF pkg/prm/docker.go:261 > Code path: /home/user1
12:35AM INF pkg/prm/docker.go:263 > Cache path: /home/user1/.pdk/prm/cache
12:35AM INF pkg/prm/docker.go:265 > Additional Args: []
12:35AM ERR pkg/prm/exec.go:29 > Error executing tool puppetlabs/ra10ke: Error response from daemon: No such image: pdk:puppet-7.0.0_puppetlabs-ra10ke_0.1.0
Error: Error response from daemon: No such image: pdk:puppet-7.0.0_puppetlabs-ra10ke_0.1.0

```

**What versions are you running?:**
 - PopOS 21.10
 - Docker 20.10.12
 - prm 0.1.0 36276c0 2022/01/31

**Additional context**

### PR DESCRIPTION
**Pull request by chelnak**
This PR fixes #139 

Prm was defaulting to a version of puppet-agent that did not exist on dockerhub. This caused execution to fail unless the user manually changed the version to a valid one.

This PR bumps the default version of puppet-agent to 7.15.0.

### CODE REVIEW

File: cmd/install/install.go [hunk 1]
```diff
@@ -63,6 +63,7 @@ func (ic *InstallCommand) executeInstall(cmd *cobra.Command, args []string) erro
 		if dirErr != nil {
 			return fmt.Errorf("Could not create tempdir to clone tool to: %v", err)
 		}
+		fmt.Println(ic.InstallPath)
```
Comment (petergmurphy) [inline cmd/install/install.go:66]: Will need to be removed

Comment (chelnak) [reply cmd/install/install.go:66]: Good spot 😬
